export const colorsLight = {
  PRIMARY_COLOR: "#6D9493",
  UNFILLED_COLOR: "#EBF1ED",

  // Background color
  BACKGROUND_SCREEN_COLOR: "#FFFFFF",

  // Text color
  PRIMARY_TEXT_COLOR: "#1C1C21",
  SECONDARY_TEXT_COLOR: "#777B85",
  DISABLED_TEXT_COLOR: "#BABBBF",

  // TextInput color
  BACKGROUND_TEXT_INPUT_COLOR: "#F8F8F8",

  // GRAY
  GRAY_LIGHT: "#F8F8F8",
  GRAY_ONBOARDING: "#CDD1D0",
  GRAY_02: "#F1F3F4",
  GRAY_03: "#777B85",
  GRAY_DIVIDER: "#F2F2F2",
  GRAY_04: "#E5E6E9",
  GRAY_BR: "#F1F1F1",
  GRAY_05: "#CBCBCB",
  GRAY_LIST_CHAT: "#FCFCFC",

  // BLUE_MAGENTA
  BLUE_MAGENTA_LIGHT: "#C8C8D0",

  // NEUTRAL
  NEUTRAL_50: "#727084",

  //FILL
  FILL_COLOR_LIGHT: "#74748014",
  FILL_COLOR_MEDIUM: "#3C3C431A",
  FILL_COUNTER: "#EEE4DB",
  FILL_COUNTER_QUIZZES: "#F7E3C2",
  FILL_QUIZZES_QUESTION_CARD: "#7D99E2",

  //GREEN COLOR
  GREEN: "#708873",

  // Error color
  ERROR: "#DC6358",

  // Alert color
  SUCCESS_COLOR: "#36B37E",
  WARNING_COLOR: "#EAB55C",
  ERROR_COLOR: "#DC6358",
  INFO_COLOR: "#A3A1AF",

  // Basic color
  WHITE: "#FFFFFF",
  BLACK: "#000000",

  // Counter colors
  ACCENT_COLOR: "#D9B9B4",

  // Verses card colors
  BORDER_GRAY_COLOR: "#F1F1F1",
};
