/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Constants from 'expo-constants';

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: Constants.expoConfig?.extra?.awsCognitoIdentityPoolId,
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: Constants.expoConfig?.extra?.awsUserPoolsId,
  aws_user_pools_web_client_id: Constants.expoConfig?.extra?.awsUserPoolsWebClientId,
  oauth: {
    domain: Constants.expoConfig?.extra?.domain,
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'meanttobe://oauth/',
    redirectSignOut: 'meanttobe://signout/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: ['EMAIL', 'PHONE_NUMBER'],
  aws_cognito_social_providers: ['AMAZON', 'APPLE'],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: Constants.expoConfig?.extra?.awsUserFilesS3Bucket,
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
